### ISSUE TITLE
Setup and installation not documented

### ISSUE THREAD

**Issue by riklund** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#144]
Needs improved README file to indicate how setup and installation is done.

**Comment by emiln** [comment]
Hello, @riklund. This information is currently only available after signing a Non-Disclosure Agreement due to the commercially sensitive nature of the information. If you are interested in actually installing and running FizzBuzzEnterpriseEdition you should contact us about finding the right pricing model for your business.
