### ISSUE TITLE
I didnt get hired!!!!!!!!!!!

### ISSUE THREAD

**Issue by degozaru** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#162]
fUCK u fFAMO i printed OUt all this fuKING 
code n my empLOYER NEVER cal me back

fuck u fam oK?

**Comment by Mikkeren** [comment]
I apologize that we have not clarified that this code is too high level for use in employment processes, and you would not be hired at a startup by presenting it, since they will be expecting a lower standard of code quality.

This code is for enterprise use only, which is why we have made it robust and scalable.

Besides our official stance as a company is that you should not be copying this for job interviews, you should instead be designing solutions according to the standard guidelines appropriate for your expected level of employment.
