### ISSUE TITLE
This should be rewritten in golang

### ISSUE THREAD

**Issue by jmoz** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#198]
goroutines would improve efficiency.

**Comment by Mikkeren** [comment]
I am afraid we need more data, to back this hypothesis.

Our internal research have proven that golang is not ready for deployment on an enterprise scale.
It is after all only 3 years old, and a relatively new player on the field. We cannot risk our entire infrastructure by introducing an untested element into the mix.

**Comment by russel** [comment]
For the record, it must be noted that Go has existed since 2007, being released to the public in 2009. However, as everyone knows, any software with a version number < 1.0 is not for production use. Go reached 1.0 in 2012-03, hence the reference to 3 years: Go has only been available for production use for 3 years. The fact that Google, Canonical, Docker, CloudFlare and many others base their core operations on the use of production ready Go is clearly not enough evidence for this organization to take that risk.

**Comment by arunanshub** [comment]
Golang slow. Java fast. That's it.

The corporate has decided your face.
