### ISSUE TITLE
What is wrong with you people?

### ISSUE THREAD

**Issue by eric-smithson** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#301]
why

**Comment by Dmitry-Me** [comment]
Thank you for bringing this up. We need to discuss this issue in details - a meeting room, a projector, slides, etc.

**Comment by eric-smithson** [comment]
thanks

**Comment by timtro** [comment]
@eric-smithson Is the concept of parody lost on you, or is your sarcasm lost on me?

**Comment by GaryRayman** [comment]
@Dmitry-Me I think we'll need a meeting to plan that meeting.

**Comment by ErikaRedmark** [comment]
@eric-smithson to answer your question... it all started a couple billion years ago and it's only gotten worse.

I suggest closing this issue as 'Won't Fix' so that engineering resources are not spent on a personnel problem that by all accounts is unsolvable. I'd go as far as to argue that if there wasn't indeed something wrong with us, this project wouldn't even exist. Think of how many non-jobs we didn't create and how many more non-jobs are left to not make if we suddenly decided to scrap this entire project in favour of some hackerish one-liner solution in some so-called "advanced" language.

**Comment by eric-smithson** [comment]
@ErikaRedmark Thank you. I will close this issue and rethink my decision of living in this world.
