### ISSUE TITLE
CCPA Compliance

### ISSUE THREAD

**Issue by Plazmaz** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#451]
Hi, please confirm that this project is CCPA compliant.
Related to #337 and #390.
The easiest solution is to just not run in California or Europe.

**Comment by wizzwizz4** [comment]
Since we are not a data processor, these regulations do not apply. The users' machines are _independently_ selling the user's emails to data aggregation companies and wiring us the money; by signing the EULA, the user explicitly agrees that it is not by the Company's direction that they decided to use the FizzBuzzEnterpriseEdition Internet-Enabled _epistola-venalis_ Installation Service.

Please close this issue.
