### ISSUE TITLE
We should port to Rust

### ISSUE THREAD

**Issue by zimmah** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#702]
I heard Rust is better, so we need to redo the whole project in Rust

**Comment by blagae** [comment]
Your request has been denied by HR due to referencing errors. They have found it impossible to get candidates to move to our main offices and borrow us their work time at the same time. Moreover, the implementation of `Clone` on `Rustacean` entities has been stuck in architecture committee for years.

Please close this issue because it makes every `Rustacean<'a>` who reads this expect that they will be able to mutate their `Career<'a>` during their lifetime.

**Comment by GEOEGII555** [comment]
Please see #694 

C++ can be faster if used correctly.
